blank_issues_enabled: false
contact_links:
  - name: 🆘 I need Help
    url: https://github.com/octokit/octokit.js/discussions/new?category_id=66179
    about: Got a question? An idea? Feedback? Start here.
