name: Issue/PR response
permissions:
  issues: write
  pull-requests: write
on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened
jobs:
  respond-to-issue:
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' && github.actor != 'githubactions[bot]' && github.actor != 'octokitbot' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine issue or PR number
        id: extract
        run: echo "NUMBER=${{ github.event.issue.number || github.event.pull_request.number }}" >> "$GITHUB_OUTPUT"

      - name: Respond to issue or PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ steps.extract.outputs.NUMBER }}
       - name: OS Aplet for Ekosystém build jobs-on
            
